### ISSUE TITLE
Fix DNS so we can enforce HTTPS

### ISSUE THREAD

**Issue by logankilpatrick** [packaging-con/packaging-con.github.io#4]
@wolfv any idea what we need to do still for this? The not secure messages make me sad

**Comment by wolfv** [comment]
I clicked the button. Hope that does it! :tada:

<img width="686" alt="Screenshot 2021-08-13 at 09 43 45" src="https://user-images.githubusercontent.com/885054/129322382-fd19808c-8492-44b3-87e0-a5732e591345.png">

**Comment by logankilpatrick** [comment]
Thank you!
